CC=g++
CFLAGS=-I.
directory=build

all:
	mkdir -p $(directory)
	$(CC) $(CFLAGS) src/1_brute_force.cpp -o $(directory)/1_brute_force
	$(CC) $(CFLAGS) src/2_bmh.cpp -o $(directory)/2_bmh
	$(CC) $(CFLAGS) src/3_bm.cpp -o $(directory)/3_bm
	$(CC) $(CFLAGS) src/4_finite_automata.cpp -o $(directory)/4_finite_automata
	$(CC) $(CFLAGS) src/5_kmp.cpp -o $(directory)/5_kmp
